apiVersion: apps/v1
kind: Deployment
metadata:
  name: activation
  labels:
    app: activation
  namespace: oss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activation
  template:
    metadata:
      labels:
        app: activation
    spec:
      containers:
        - name: activation
          image: 676906203200.dkr.ecr.ap-northeast-2.amazonaws.com/oss-activation:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failure