apiVersion: apps/v1
kind: Deployment
metadata:
  name: oss-activation
  labels:
    app: oss-activation
  namespace: oss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oss-activation
  template:
    metadata:
      labels:
        app: oss-activation
    spec:
      containers:
        - name: oss-activation
          image: 496278789073.dkr.ecr.ap-northeast-2.amazonaws.com/oss-activation:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10